# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT nsc.wsgi

beta_settings:
    cloud_sql_instances: nsc-blacklist-api:us-central1:django-base

runtime_config:
  python_version: 3
# [END runtime]
